// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSystemInfo():Promise<main.SystemInfo>;

export function Greet(arg1:string):Promise<string>;

export function ImportCertificate(arg1:main.ImportParams):Promise<main.ImportResult>;

export function ListCertificates():Promise<Array<main.CertificateInfo>>;

export function SelectCertificateFile():Promise<string>;

export function ValidateCertificate(arg1:string):Promise<boolean>;
