// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportCertificate(arg1) {
  return window['go']['main']['App']['ImportCertificate'](arg1);
}

export function ListCertificates() {
  return window['go']['main']['App']['ListCertificates']();
}

export function SelectCertificateFiles() {
  return window['go']['main']['App']['SelectCertificateFiles']();
}

export function ValidateCertificate(arg1) {
  return window['go']['main']['App']['ValidateCertificate'](arg1);
}
